# Generated by Django 4.0.3 on 2022-03-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='city',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
